version: "3.8"
services:
  web:
    build: ./app
    image: 133777440157.dkr.ecr.us-east-1.amazonaws.com/workshop2:workshop2_web #task5
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.cxsu8iia4scb.us-east-1.rds.amazonaws.com  #task5
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-52-204-57-117.compute-1.amazonaws.com #task5
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 133777440157.dkr.ecr.us-east-1.amazonaws.com/workshop2:workshop2_nginx  #task5
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: